### Lists of stock tickers ###

allowed_countries = ['ICELAND', 'USA', 'NORWAY','NORWAY_SIMILAR','DENMARK', 'DENMARK_SIMILAR','UK']


# Icelandic stock tickers (31 in total)
ICELAND = [
    'ALVO.IC','AMRQ.IC','ARION.IC','BRIM.IC','EIK.IC','EIM.IC','FESTI.IC','HAGA.IC','HAMP.IC','HEIMAR.IC','ICESEA.IC',
    'ICEAIR.IC','ISLAX.IC','ISB.IC','ISF.IC','JBTM.IC','KALD.IC','KLDVK.IC','KVIKA.IC','KLAPP.IC','NOVA.IC',
    'OCS.IC','OLGERD.IC','REITIR.IC','SIMINN.IC','SJOVA.IC','SKAGI.IC','SKEL.IC','SOLID.IC','SVN.IC','SYN.IC'
]

USA = ['AAPL','NVDA','MSFT','GOOG','AMZN','AVGO','META','TSLA','BRK-B','LLY','JPM','WMT','XOM','V','JNJ','MU','MA','COST','ORCL','CVX']

NORWAY = ['KOG.OL','TOM.OL','NHY.OL','YAR.OL','NOD.OL','ATEA.OL','BOUV.OL','KIT.OL','MEDI.OL','PHO.OL','SCATC.OL','NEL.OL','BRG.OL','ABG.OL']

NORWAY_SIMILAR = ['MOWI.OL','ENTRA.OL','WAWI.OL','EPR.OL','KID.OL','AKVA.OL','SBO.OL','LSG.OL','NAS.OL','VEI.OL','TEL.OL','GJF.OL','EQNR.OL','POL.OL']

DENMARK = ['NOVO-B.CO','GMAB.CO','ZEAL.CO','BAVA.CO','AMBU-B.CO','COLO-B.CO','DEMANT.CO','VWS.CO','FLS.CO','ROCK-B.CO','CARL-B.CO','NKT.CO','PNDORA.CO','ISS.CO']

DENMARK_SIMILAR = ['SCHO.CO','JDAN.CO','MAERSK-B.CO','MATAS.CO','RBREW.CO','RBLN-B.CO','FED.CO','FFARMS.CO','KBHL.CO','AGAT.CO','RTX.CO','TRYG.CO','SOLAR-B.CO','NORTHM.CO']

UK = ["SHEL.L","HSBA.L","RR.L","LLOY.L","NG.L","MKS.L","DGE.L","GSK.L","BA.L","BARC.L","SBRY.L","LGEN.L","SGE.L","LSEG.L",]
